### ISSUE TITLE
App Description and Sketch

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/dash_of_spice#5]

**Comment by cmmclaug** [comment]
The description should be about 200-300 words and live in the README.md file of your GitHub.com repository. The sketch should be linked in the README.md file of your GitHub.com repository underneath the high level description so that the image shows up on GitHub.

Example description

The app contains a landing page that shows the distribution (depending on data type, bar chart, density chart etc) of dataset factors (hypertension, physical disabilities etc.) colored coded according to whether patients showed up or didn't show up for an appointment. From a dropdown list, users can filter out variables from the distribution display, by patient demographics (i.e. only show female patients), by appointment data (i.e. if SMS was sent), and finally by the date range of appointments. A different dropdown menu will allow users to re-order variables according to the probability of patients being a no-show or in alphabetical order to comorbidities. Users can compare the distribution of co-morbidities by scrolling down through the app interface.

**Comment by rachelywong** [comment]
Just wanted to upload a first draft of the sketch, and one after our Slack discussion. I've also included the
 whiteboard mockup of our initial thoughts. 

whiteboard mockup: ![Whiteboard 1 -01](https://user-images.githubusercontent.com/45707735/104483454-fc2c4f00-557c-11eb-8e36-b8337df2f516.png)

first draft: ![532 App Sketch](https://user-images.githubusercontent.com/45707735/104483310-d30bbe80-557c-11eb-8494-fd7689c15482.png)

second draft: ![Screen Shot 2021-01-12 at 9 14 39 PM](https://user-images.githubusercontent.com/45707735/104483308-d2732800-557c-11eb-89a3-23043d1ac00a.png)

**Comment by rachelywong** [comment]
I updated the sketch a bit based on the new feedback in Slack:

![Screen Shot 2021-01-13 at 11 16 09 AM](https://user-images.githubusercontent.com/45707735/104498612-c85b2480-5590-11eb-9067-419646a01218.png)

I also added a second sketch that shows if you scroll down in the “Top 5 Section” you can select the bottom country too and clicking the arrow in the plots area moves the plots by one to show the next ranking plot. We don't have to use this though, just thought it could help explain our sketch a bit more!

![Screen Shot 2021-01-13 at 11 16 15 AM](https://user-images.githubusercontent.com/45707735/104498689-e4f75c80-5590-11eb-842e-73c63e388bcd.png)
