### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by debanandasarkar** [UBC-MDS/dash_of_spice#55]
Hi Team,

Great job with your dashboard. My teammates and I were discussing your work and we found the idea behind your application is quite interesting are closely related to the rising mental concerns in the society now. The usage scenario in your proposal has articulated your idea very well.

Congrats, for putting up an awesome app. 

Here is what we all liked about your application:
- The layout of your graphs and global filters looks very nice.
- The App sketch gives a clear description of the functionalities of your application
- We liked the vast range of interactive options provided. 
- We also liked the way you are hiding the line plot when we clear the countries drop down.

Here is some improvements that we think may be helpful to your application:
- There is a scroll bar in your graph, you may want to resize the frame or the graph to get rid of it
- The year on your x-axis is now showing vertically, which could be hard to read. Maybe you would want to change the angle of it
- Selecting the country doesn't see to make a difference in the dashboard, maybe we are missing something here, but a clear difference after changing the selection might be more helpful.
- You may use a different color for the reset button and top 10 countries list.

Overall, you have done an amazing job and we all wish you the best with the final milestone.

Best regards,
DSCI532 Group4

**Comment by rachelywong** [comment]
Hi Debananda and team!

Thank you so much for the feedback, we've taken it into consideration!

Specifically:
- Resized graphs to remove the scroll bar
- Fixed the plots so that the axes are easy to read
- Selecting countries has been implemented!
- Color scheme and overall layout has been addressed

You can check out our new app [here](https://happy-navvy-r.herokuapp.com/) or from our new GitHub page [here](https://github.com/UBC-MDS/dash_of_spice-R)
